### ISSUE TITLE
http reqeuest block

### ISSUE THREAD

**Issue by hlyzfxt** [lunarmodules/copas#100]
When I modify the system time, I change it to a future time. For example, the current time is 2020.07.07, and it is modified to 2020.07.09. When I send an http request, the request will be block and will not time out.

**Comment by ildar** [comment]
You sure it is a wrong behavior of `copas`? Might be a problem in another
place?

**Comment by hlyzfxt** [comment]
--- Sets the timeout for the current coroutine.
  -- @param delay delay (seconds), use 0 to cancel the timerout
  -- @param callback function with signature: `function(coroutine)` where coroutine is the routine that timed-out
  -- @return true
  function copas.timeout(delay, callback)
    local co = coroutine.running()
    local existing_timer = timeout_register[co]

    if existing_timer then
      timerwheel:cancel(existing_timer)
    end

    if delay > 0 then
      timeout_register[co] = timerwheel:set(delay, callback, co)
    else
      timeout_register[co] = nil
    end

    return true
  end
end
in line 931 to 952.

yes, i am sure.
When I change the system time, the value of the variable delay will be very large. If I ignore the abnormal value, the http request can be sent normally without getting block.But I am not sure if it will cause other problems.

    if delay > 0 then
      if delay > 60 * 5 then
        delay = 30
      end
      timeout_register[co] = timerwheel:set(delay, callback, co)
    else
      timeout_register[co] = nil
    end

**Comment by Tieske** [comment]
Sorry for the long delay.

That function for a timeout is a very low level timeout feature. It is the underlying mechanism for the socket timeouts. You should not be using that directly in user code.

The http module used its own timeout (fixed at 30 seconds), until it was fixed in version 4.1.0.

I'll assume this can been resolved. If not please reopen.
