### ISSUE TITLE
SNI support not working for copas.http

### ISSUE THREAD

**Issue by fedenunez** [lunarmodules/copas#109]
copas.http with a https URL that requires SNI will not work.

I tried to define the new (copas 3) wrap&sni parameters as defined in https://github.com/keplerproject/copas/pull/105, but it looks like [http.lua ](https://github.com/keplerproject/copas/blob/master/src/copas/http.lua#L348) is not supporting SNI, and it will force the default protocol & mode triggering the backward compatibility mode. 

In my understanding, copas.http should detect the https protocol and in that case, parse the domain and automatically define the SNI. It should also honor the user request and just pass whatever the user define inside SNI.

If you agree, I can send a pull request with the proposed change.

**Comment by Tieske** [comment]
@fedenunez apologies for the long delay. A PR would be most welcome!
