### ISSUE TITLE
copas 3.0.0-2 not published in luarocks.org

### ISSUE THREAD

**Issue by hishamhm** [lunarmodules/copas#113]
Any blockers for this? I'm trying to run the LuaRocks test suite with Lua 5.4 and I hit the 3.0.0-1 issue.

**Comment by Tieske** [comment]
uploaded, must have missed it somewhere...

**Comment by hishamhm** [comment]
@Tieske thanks! I just tried the latest rockspec 3.0.0-3 and I noticed it is forcing luasocket 3.0rc2, and not the latest luasocket 3.0.0 that was recently released — is there an incompatibility somewhere?

**Comment by Tieske** [comment]
yes, test suite fails on the new version. Hence until resolved, we're pinning to the old version to be safe.
