### ISSUE TITLE
copas.lua attempt to index local 'new_q' (a number value)

### ISSUE THREAD

**Issue by AMD-NICK** [lunarmodules/copas#116]
Lua 5.1

The place where the error occurred:
https://github.com/lunarmodules/copas/blob/f49455999f3e7ee6cd56b964b4b0e11512744a9f/src/copas.lua#L963

Copas is used exclusively for asynchronous https requests. This is the first time I've noticed this error, and it caused copas.loop to stop working

Below is the code I used to run the script

```lua
local copas = require("copas")

copas.setErrorHandler(function(err, thread)
	local tr = debug.traceback()
	PRINT("copas.setErrorHandler GLOBAL", err, thread, tr) -- the error didn't appear here
end, true)

local res,err = pcall(copas.loop, function()
	print("Started")
end)

if not res then
	-- Stop working. Reason: ~/.luarocks/share/lua/5.1/copas.lua:904: attempt to index local 'new_q' (a number value)
	-- Note: My line number is 904 instead of 963 as pointed in issue. I think It's because luarocks downloads a bit older version of copas for lua 5.1
	print("Stop working. Reason: " .. tostring(err))
end

```

You can see my http request function here: https://github.com/TRIGONIM/ggram/blob/061387978c8c73ff2437749119e34752fbbcbc2e/lua/ggram/glua/http_async.lua#L61-L83

A second before the script crashed, there was a failed callback on line 80 in the link above

**Comment by Tieske** [comment]
What is your Copas version? can you check using `luarocks list copas` ?

**Comment by AMD-NICK** [comment]
`3.0.0-3`

**Comment by Tieske** [comment]
ok, then line 904 makes sense; https://github.com/lunarmodules/copas/blob/v3_0_0/src/copas.lua#L904

**Comment by Tieske** [comment]
can you clarify this statement: "A second before the script crashed, there was a failed callback on line 80 in the link above"?

Also; can you reproduce this?

**Comment by AMD-NICK** [comment]
> can you clarify this statement: "A second before the script crashed, there was a failed callback on line 80 in the link above"?

A second before the script crashed, the code in this line was executed: https://github.com/TRIGONIM/ggram/blob/061387978c8c73ff2437749119e34752fbbcbc2e/lua/ggram/glua/http_async.lua#L80

I'm not sure if it's related, but I decided to point it out

> Also; can you reproduce this?

I don't think so. It was really an anomalous bug that I just decided to report. I've been using copas to make about 5 HTTPS requests per second for quite some time, and about once a day I have to restart copas because of a timeout error, but no error with new_q has happened yet

**Comment by Tieske** [comment]
so the errohandler not picking up the error makes sense. Since the errorhandler is set for the coroutine on which you call it.

Here's the intended use; setting the errorhandler at the start of your thread:
```lua
local res,err = pcall(copas.loop, function()
	copas.setErrorHandler(function(err, thread)
		local tr = debug.traceback()
		PRINT("copas.setErrorHandler GLOBAL", err, thread, tr) -- the error didn't appear here
	end, true)

	print("Started")
end)
```

**Comment by Tieske** [comment]
as for the error `attempt to index local 'new_q' (a number value)` that can actually occur. When completing a coroutine (eg. exiting) with return values different from what Copas expects (arg 1: socket, arg 2: queue (read/write/sleep) )

That actually is a bug.
