### ISSUE TITLE
Error "descriptor too large for set size"

### ISSUE THREAD

**Issue by AMD-NICK** [lunarmodules/copas#164]
I have written an express.js port based on copas. While testing my application via loader.io, I send thousands of requests to my application and after some time I encounter the mentioned error.

I have a theory that it might be related to the locking mechanism in copas in some way. Below I provide an example of how to reproduce the error. In addition to express, the application uses my implementation of mysql connection pool, which executes queries using luasocket + copas exclusively. If you set the number of connections and workers to low in the pool settings, the pool will not have time to execute requests and soon there will be 1000 unprocessed requests in copas.queue (pool.queries) and the application will crash.

I think that this problem should be tried to solve in copas but if it is impossible (I have tried some variants), are there any ways to handle this error?

## Used libraries:

- lua-express: https://github.com/TRIGONIM/lua-express/tree/main
- luasocket-mysql with connection pool: https://github.com/TRIGONIM/luasocket-mysql/

## Reproduce example:

![screenshot_2023-11-18_10 11 21@2x](https://github.com/lunarmodules/copas/assets/9200174/17d6da72-2ce4-497a-9c4f-c0f23669e8ef)

```lua
local host, port = os.getenv("MYSQL_HOST"):match("([^:]+):?(%d*)")
local mysql_pool = require("mysql.pool").new({
	pool_size  = 1,
	workers    = 1,
	mysql_opts = {
		host      = host,
		port      = port,
		user      = os.getenv("MYSQL_USER"),
		password  = os.getenv("MYSQL_PASS"),
		database  = os.getenv("MYSQL_NAME"),
		charset   = "utf8mb4",
	},
})

local express = require("express")
local app = express()

local request_num = 0
app:use(function(_, _, next)
	request_num = request_num + 1
	print("✅ request_num: " .. request_num)
	next()
end)

app:post("/", function(req, res, next)
	mysql_pool:query("SELECT 1 + 2 as res", function(q_res, q_err, q_errcode, q_sqlstate)
		res:send("res: " .. q_res[1].res)
	end, 50)

	print("current queries pool size", mysql_pool.queries:get_size())
end)

app:get("loaderio-hash.txt", function(req, res)
	res:send("loaderio-hash")
end)

app:listen(3000)
```

## loader.io settings

I chose the POST method out of habit, but it probably doesn't matter.

![screenshot_2023-11-18_10 12 50@2x](https://github.com/lunarmodules/copas/assets/9200174/8fea291f-6a77-4664-92bc-12844a8abdf0)

**Comment by AMD-NICK** [comment]
This could possibly be related: https://github.com/TRIGONIM/lua-express/blob/cd66aa981a0c1c2ff744a16bc887dfaa2658490e/lua/express/application.lua#L275

**Comment by Tieske** [comment]
This is a hard one, since it is tied to the underlying machinery; https://stackoverflow.com/questions/7976388/increasing-limit-of-fd-setsize-and-select
