### ISSUE TITLE
Queue destroying on stopping

### ISSUE THREAD

**Issue by ventureoo** [lunarmodules/copas#168]
Destroying the queue on stop or finish happens either when the items in the queue itself becomes 0, or after a timeout. But originally I thought that queue destroying occurs when the queue becomes empty and all workers have finished their work. So the queue is destroyed before the worker with the last element finishes its job. This may be only my problem, but if this is the expected behavior, it would be nice to clarify it in the documentation, as there are a number of cases where we want to expect not only the queue to be empty, but all its workers to complete. E. g.:

```lua
local copas = require("copas")

local function main()
    local queue = copas.queue.new()

    for i = 1, 3 do
        queue:push(i)
    end

    queue:add_worker(function (number)
        copas.pause(2)
        print("Queue handler #" .. number .. " done")
    end)
    queue:finish()
    print("Exit from parent thread")
end

copas.addthread(main)
copas()

```

Result is:
```
> luajit queue_test.lua
Queue handler #1 done
Queue handler #2 done
Exit from parent thread
Queue handler #3 done
```

I use the following code to guarantee the behavior when the queue ends with all the workers:

```lua
local copas = require("copas")

local function main()
    local queue = copas.queue.new()
    local tasks = 0

    for i = 1, 3 do
        tasks = tasks + 1
        queue:push(i)
    end

    queue:add_worker(function (number)
        copas.pause(2)
        print("Queue handler #" .. number .. " done")
        tasks = tasks - 1
    end)
    queue:finish()

    while tasks > 0 do
        print("Waiting for the handlers to complete...")
        copas.pause(1)
    end
    print("Exit from parent thread")
end

copas.addthread(main)
copas()
```

Result is:

```
Queue handler #1 done
Queue handler #2 done
Waiting for the handlers to complete...
Waiting for the handlers to complete...
Queue handler #3 done
Exit from parent thread
```

I also tried to use queue:get_workers() to check which workers were still working, but that produced the same result as the first one.  But maybe you have a better solution. Thanks.

**Comment by Tieske** [comment]
That's an interesting case. This should do the trick;

```
queue:finish()
while #queue:get_workers() > 0 do copas.pause(0.1) end
```

But I think your expectations make sense. `finish` shouldn't return until the work is done.

Internally it now create a lock used as a timeout. We can probably update that to be a semaphore to which each exiting worker releases a resource until all done. That would prevent having to do the above loop with a sleep-call.

But it would also require the worker to be running protected (which it currently doesn't), since if it errors out, the semaphore will never be released. Though that will trigger the timeout again 🤔 , so should be ok.

**Comment by ventureoo** [comment]
> That's an interesting case. This should do the trick;
> 
> ```
> queue:finish()
> while #queue:get_workers() > 0 do copas.pause(0.1) end
> ```
> 
> But I think your expectations make sense. `finish` shouldn't return until the work is done.
> 
> Internally it now create a lock used as a timeout. We can probably update that to be a semaphore to which each exiting worker releases a resource until all done. That would prevent having to do the above loop with a sleep-call.
> 
> But it would also require the worker to be running protected (which it currently doesn't), since if it errors out, the semaphore will never be released. Though that will trigger the timeout again 🤔 , so should be ok.

Thanks for reply. Yes, I was thinking about using `get_workers()`, unfortunately that doesn't work. For it's not possible to get the number of active workers after destroying the queue, since queue object redefines its metatable to `{ __index = destroyed_func }` after destroying it and `get_workers()` will always return nil+"destroyed" after finish.

https://github.com/lunarmodules/copas/blob/master/src/copas/queue.lua#L120-L129C4

**Comment by Tieske** [comment]
yep, you're right. So this needs a fix then.

**Comment by Tieske** [comment]
#168 should fix this. Can you give it a spin @ventureoo ?

**Comment by ventureoo** [comment]
> #168 should fix this. Can you give it a spin @ventureoo ?

Yes, indeed, that fixes my issue. Thanks.
